name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      IMAGE_NAME: runpod-worker-a1111
      DOCKERFILE_PATH: Dockerfile
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      MODEL_URL: ${{ vars.MODEL_URL }}
      CIVITAI_TOKEN: ${{ secrets.CIVITAI_TOKEN }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get autoclean
        docker system prune -a --volumes --force

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build --build-arg MODEL_URL=${MODEL_URL} --build-arg CIVITAI_TOKEN=${CIVITAI_TOKEN} --build-arg HF_TOKEN=${HF_TOKEN} -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
